### ISSUE TITLE
Dash to Dock not fully transparent

### ISSUE THREAD

**Issue by trgeiger** [godlyranchdressing/Minwaita#13]
I really love the look of Plank and would love for Dash to Dock to have that style, but as it is currently, there's an obvious border around the dock that kind of ruins the effect. Is this a limitation of the styling options for the dock, or is there a way to get full transparency above the "plank" portion at the bottom?

**Comment by godlyranchdressing** [comment]
It is a limitation, but that's just because of the way I did it. I'd originally styled the dock with CSS box-shadows to limit the amount of external assets used/because of laziness. GNOME Shell can't render box shadows unless the element has a background though, so the border you're seeing is a black background with 1% opacity. 

I'll just switch over to new assets for the dock. Should be pushing it tomorrow.

**Comment by trgeiger** [comment]
Awesome, looking forward to it!
