### ISSUE TITLE
Strange flickering when alt-tabbing between windows

### ISSUE THREAD

**Issue by ghost** [godlyranchdressing/Minwaita#2]
I'm unsure if this is a theming problem (I'm wondering if it's a gnome problem), but alt-tabbing between windows tends to have this strange 'resize-on-the-fly' behavior. See the attached video for a demo.

Archlinux latest with gnome 3.24. Tested on both Nvidia and intel display drivers+xorg.

Using external hosting because github doesn't allow .webms:

https://imgur.com/a/xW7jX

**Comment by godlyranchdressing** [comment]
That is indeed a theme problem. Adwaita has quite a bit of styling for its out of focus/backdrop state so what you're seeing is the window adjusting for that when focus is changed. Though the size fluctuations is definitely strange since AFAIK nothing but colours should be changing. 

Toning down the backdrop styling is on my list of things to cut but I'll be sure to prioritize it to fix this.

**Comment by godlyranchdressing** [comment]
Located the issue. The active window box-shadow dimensions doesn't match the backdrop's. Will be fixed in next commit.
